name: cubiemedia-mqtt-client
base: core20
version: '0.5.0'
summary: Gateway for different Protocols or Devices
description: |
  CubieMedia MQTT-Client for EnOcean, GPIOs and Relayboards
grade: stable
confinement: strict

architectures:
  - build-on: [ armhf, arm64 ]
    run-on: [ amd64, armhf, arm64 ]

parts:
  cubiemedia-mqtt-client:
    plugin: dump
    source: .
  python:
    source: ./src
    plugin: python
    python-packages: [ enocean ]
    stage-packages: [ python3-paho-mqtt, python3-lxml, python3-netifaces, python3-zeroconf, python3-serial, python3-requests, python3-flask, try: [ python3-rpi.gpio ] ]

apps:
  cubiemedia-mqtt-client:
    command: usr/bin/cubiemedia-mqtt-client
    plugs: [ network, network-bind, serial-port, gpio, gpio-memory-control ]
  cubiemedia-enocean:
    command: usr/bin/cubiemedia-mqtt-client enocean
    daemon: simple
    install-mode: disable
  cubiemedia-relay:
    command: usr/bin/cubiemedia-mqtt-client relay
    daemon: simple
    install-mode: disable
  cubiemedia-gpio:
    command: usr/bin/cubiemedia-mqtt-client gpio
    daemon: simple
    install-mode: disable
