title: CubieMedia MQTT-Client
name: cubiemedia-mqtt-client
base: core22
version: '0.9.1'
summary: Gateway for different Protocols or Devices
description: CubieMedia MQTT-Client for EnOcean, GPIOs, ETH008 Relayboards and Victron Energy System
grade: stable
confinement: strict

icon: src/webtool/static/logo.png
contact: info@cubiemedia.de
website: https://www.cubiemedia.de
source-code: https://github.com/CubieMedia/mqtt-client

architectures:
  - build-on:
      - armhf
    build-for:
      - armhf
  - build-on:
      - amd64
    build-for:
      - amd64

parts:
  cubiemedia-mqtt-client:
    plugin: dump
    source: .
  python:
    source: ./src
    plugin: python
    python-packages:
      - enocean
      - flask
      - paho-mqtt
      - netifaces
    stage-packages:
      - python3-paho-mqtt
      - python3-lxml
      - python3-netifaces
      - python3-zeroconf
      - python3-serial
      - python3-requests
      - python3-flask
      - on armhf:
          - python3-rpi.gpio

apps:
  cubiemedia-mqtt-client:
    command: usr/bin/cubiemedia-mqtt-client
    plugs: [ network, network-bind, serial-port, gpio-memory-control ]
  cubiemedia-sonar:
    plugs: [ network, network-bind, serial-port ]
    command: usr/bin/cubiemedia-mqtt-client sonar
    daemon: simple
    install-mode: disable
  cubiemedia-victron:
    plugs: [ network, network-bind ]
    command: usr/bin/cubiemedia-mqtt-client victron
    daemon: simple
    install-mode: disable
  cubiemedia-enocean:
    plugs: [ network, network-bind, serial-port ]
    command: usr/bin/cubiemedia-mqtt-client enocean
    daemon: simple
    install-mode: disable
  cubiemedia-relay:
    plugs: [ network, network-bind ]
    command: usr/bin/cubiemedia-mqtt-client relay
    daemon: simple
    install-mode: disable
  cubiemedia-gpio:
    plugs: [ network, network-bind, gpio-memory-control ]
    command: usr/bin/cubiemedia-mqtt-client gpio
    daemon: simple
    install-mode: disable
  cubiemedia-core:
    plugs: [ network, network-bind ]
    command: usr/bin/cubiemedia-mqtt-client core
    daemon: simple
  cubiemedia-webtool:
    plugs: [ network, network-bind, system-observe ]
    command: usr/bin/flask run
    daemon: simple
    environment:
      FLASK_APP: $SNAP/src/webtool/app.py
      FLASK_ENV: production
      FLASK_RUN_PORT: 8888
      FLASK_RUN_HOST: 0.0.0.0

