name: cubiemedia-mqtt-client
base: core20
version: '0.2'
summary: Gateway for different Protocols or Devices
description: |
  CubieMedia MQTT-Client for EnOcean, GPIOs and Relayboards
grade: devel
confinement: devmode

layout:
  /usr/lib/cubiemedia:
    bind: $SNAP/usr/lib/cubiemedia

parts:
  cubiemedia-mqtt-client:
    plugin: dump
    source: .
  python:
    source: .
    plugin: python
#    override-build: |
#      snapcraftctl build
#      pip3 install wheel
#    build-packages: [python3, python3-dev, python3-setuptools, python3-wheel, python3-paho-mqtt, python3-netifaces, python3-zeroconf, python3-rpi.gpio, python3-serial, python3-requests, python3-flask]
#    build-environment:
#      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
#    build-snaps: []
#    python-packages: [requests, netifaces, enocean, rpi.gpio, paho-mqtt]
    stage-packages: [python3-paho-mqtt, python3-netifaces, python3-zeroconf, python3-rpi.gpio, python3-serial, python3-requests, python3-flask]

architectures:
  - build-on: [armhf, arm64]
    run-on: [armhf, arm64, amd64]

apps:
  cubiemedia-mqtt-client:
    command: usr/bin/cubiemedia-mqtt-client
  enocean:
    command: usr/bin/cubiemedia-mqtt-client enocean
  relay:
    command: usr/bin/cubiemedia-mqtt-client relay
  io:
    command: usr/bin/cubiemedia-mqtt-client io

