name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint paho.mqtt ifaddr enocean pyserial requests flask werkzeug pytest miflora crc8 bleak
    - name: Analysing the code with pylint
      run: |
        pylint --disable=C,R,W,I $(git ls-files 'src/*/*.py')
