#!/bin/sh -e

snapctl set core='{"type": "core", "host": "homeassistant", "username": "mqtt", "password": "autoInstall", "learn_mode": true}'

snapctl set gpio='[{"id": 4, "function": "IN", "type": "GPIO","value": 0},
  {"id": 17, "function": "IN", "type": "GPIO", "value": 0},
  {"id": 27, "function": "IN", "type": "GPIO", "value": 0},
  {"id": 22, "function": "IN", "type": "GPIO", "value": 0},
  {"id": 18, "function": "OUT", "type": "GPIO", "value": 0},
  {"id": 23, "function": "OUT", "type": "GPIO", "value": 0},
  {"id": 24, "function": "OUT", "type": "GPIO", "value": 0},
  {"id": 25, "function": "OUT", "type": "GPIO", "value": 0}]'
snapctl set sonar='[{"type": "sonar", "device": "/dev/ttyS0", "update_interval": 10, "offset": 0}]'
snapctl set relay='[]'
snapctl set victron='[]'
snapctl set enocean='[]'
snapctl set demo='[{"id": "aa:bb:cc:dd:ee:ff", "type": "Demo-Device", "client_id": "Demo_Client", "dbm": "44"},
                        {"id": "Bärbel", "type": "Demo-Device", "client_id": "Demo_Client", "dbm": "33"},
                        {"id": "11:22:33:44:55:66", "type": "Demo-Device", "client_id": "Demo_Client", "dbm": "22"}]'
