#!/bin/sh -e

snapctl set cubiemedia='`cat ../../src/config/cubiemedia.json`'

snapctl set serial='`cat ../../src/config/serial.json`'

snapctl set gpio='`cat ../../src/config/gpio.json`'
snapctl set sonar='`cat ../../src/config/sonar.json`'
snapctl set relay='`cat ../../src/config/relay.json`'
snapctl set victron='`cat ../../src/config/victron.json`'
snapctl set enocean='`cat ../../src/config/enocean.json`'
